encomi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
]

shop/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.base, name='base'),
    path('home/<seller_name>', views.home, name='home'),
    path('shop/<seller_name>', views.shop, name='shop'),
    path('item/<seller_name>/<id>', views.item, name='item'),
    path('cart/<seller_name>', views.cart, name='cart'),
    path('checkout/<seller_name>', views.checkout, name='checkout'),
    path('thankyou/<seller_name>', views.thankyou, name='thankyou'),
    path('create_order/<seller_name>', views.create_order, name='create_order'),
    path('cart_preview/<seller_name>', views.cart_preview, name='cart_preview'),
    path('cart_total/<seller_name>', views.cart_total, name='cart_total'),
    path('shop_items/<seller_name>', views.shop_items, name='shop_items'),

    path('become_seller/', views.become_seller, name='become_seller'),
    path('register/', views.register_user, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('help/<seller_name>', views.help, name='help'),
    path('help_faqs/<seller_name>/<type>', views.help_faqs, name='help_faqs'),


    path('dashboard/home/<seller_name>', views.dashboard, name='dashboard'),
    path('dashboard/listings/<seller_name>', views.listings, name='listings'),
    path('dashboard/deliveries/<order_id>/<seller_name>', views.deliveries, name='deliveries'),
    path('dashboard/settings/<seller_name>', views.settings, name='settings'),
    path('dashboard/listings_items/<seller_name>', views.listings_items, name='listings_items'),
    path('dashboard/listings_new/<seller_name>', views.listings_new, name='listings_new'),
    path('dashboard/listings_new_customization_group/<id>/<seller_name>', views.listings_new_customization_group, name='listings_new_customization_group'),
    path('dashboard/listings_new_customization_option/<id>/<count>/<seller_name>', views.listings_new_customization_option,
         name='listings_new_customization_option'),
    path('dashboard/listings_new_image/<seller_name>', views.listings_new_image, name='listings_new_image'),
    path('dashboard/listings_new_save/<seller_name>', views.listings_new_save, name='listings_new_save'),
    path('dashboard/listings_edit/<seller_name>/<id>', views.listings_edit, name='listings_edit'),
    path('dashboard/listings_edit_save/<seller_name>/<id>', views.listings_edit_save, name='listings_edit_save'),
    path('dashboard/deliveries_selected/<seller_name>/<order_id>', views.deliveries_selected, name='deliveries_selected'),
    path('dashboard/update_order_status/<seller_name>/<order_id>/<order_status>', views.update_order_status,
         name='update_order_status'),
    path('dashboard/update_settings_content/<seller_name>/<content>', views.update_settings_content,
         name='update_settings_content'),
    path('dashboard/create_settings_faq/<seller_name>', views.create_settings_faq,
         name='create_settings_faq'),
    path('dashboard/delete_settings_faq/<seller_name>', views.delete_settings_faq,
         name='delete_settings_faq'),
    path('dashboard/payments/<seller_name>', views.payments, name='payments'),


    path('seller_policy/<seller_name>', views.seller_policy, name='seller_policy'),
    path('privacy_policy/<seller_name>', views.privacy_policy, name='privacy_policy'),
    path('TOU/<seller_name>', views.TOU, name='TOU'),
    path('about/<seller_name>', views.about, name='about'),

    path('scrape/<seller_name>', views.scrape, name='scrape')


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, UserManager


class SellerPolicies(models.Model):
    shipping_general_information = models.TextField(max_length=10000, null=True, blank=True)
    shipping_customs_and_taxes = models.TextField(max_length=10000, null=True, blank=True)

    accepts_returns = models.BooleanField(default=False, null=True, blank=True)
    accepts_exchanges = models.BooleanField(default=False, null=True, blank=True)
    accepts_cancellations = models.BooleanField(default=True, null=True, blank=True)

    contact_within = models.IntegerField(default=3)
    ship_back_within = models.IntegerField(default=7)
    request_cancellation = models.CharField(default='before item has shipped', max_length=100)

    returns_conditions = models.TextField(max_length=10000, null=True, blank=True)
    returns_questions = models.TextField(max_length=10000, null=True, blank=True)
    privacy = models.TextField(max_length=10000, null=True, blank=True)

    last_updated = models.DateTimeField(null=True, auto_now=True)


class Seller(models.Model):
    name = models.CharField(max_length=50, null=True)
    email = models.EmailField(null=True)
    logo = models.ImageField(upload_to="seller_logos", default="logos/logo.png")
    etsy_url = models.CharField(max_length=300, null=True)
    delivery_price = models.FloatField(default=0)
    delivery_days_min = models.IntegerField(default=4)
    delivery_days_max = models.IntegerField(default=7)

    password = models.CharField(max_length=12, null=True, blank=True)

    favicon = models.ImageField(null=True, default="icons/favicon.png")

    img_landing_page = models.FileField(null=True)
    img_landing_page_mobile = models.FileField(null=True)
    img_shop_page = models.FileField(null=True)
    img_shop_page_mobile = models.FileField(null=True)
    img_item_page = models.FileField(null=True)
    img_item_page_mobile = models.FileField(null=True)

    policies = models.ForeignKey(SellerPolicies, on_delete=models.SET_NULL, null=True, blank=True)

    registration_code = models.CharField(max_length=12, null=True, blank=True)

    pp_tracking_id = models.CharField(max_length=40, null=True, blank=True)
    pp_email = models.EmailField(null=True, blank=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    title = models.CharField(max_length=30)
    seller = models.ForeignKey('Seller', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Image(models.Model):
    image = models.ImageField(upload_to="item_images")
    item = models.ForeignKey('Item', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.image.name


ITEM_STATUS_CHOICES = {
    ('In stock', 'In stock'),
    ('Out of stock', 'Out of stock'),
    ('Deactivated', 'Deactivated'),
}


class Item(models.Model):
    title = models.CharField(max_length=1200)
    keywords = models.CharField(blank=True, null=True, max_length=1200, default='All')
    price = models.FloatField(blank=True, null=True)
    old_price = models.FloatField(blank=True, null=True)
    details = models.TextField(max_length=5000, blank=True, null=True)
    description = models.TextField(max_length=5000, blank=True, null=True)
    materials = models.TextField(max_length=5000, blank=True, null=True)
    categories = models.ManyToManyField(Category, null=True, blank=True)
    seller = models.ForeignKey('Seller', null=True, on_delete=models.CASCADE)
    sold_counter = models.IntegerField(default=0)
    status = models.CharField(max_length=100, default='In stock', choices=ITEM_STATUS_CHOICES)

    def __str__(self):
        return self.title


class StyleGroup(models.Model):
    type = models.CharField(max_length=30)
    item = models.ForeignKey('Item', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.type


class Style(models.Model):
    title = models.CharField(max_length=30)
    price = models.FloatField(null=True, blank=True)
    style_group = models.ForeignKey('StyleGroup', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


ORDER_STATUS_CHOICES = {
    ('delivered', 'delivered'),
    ('on the way', 'on the way'),
    ('not handled', 'not handled'),
}


class ParentOrder(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    street_name = models.CharField(max_length=200)
    house_number = models.CharField(max_length=200)
    postal_code = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    message = models.TextField(max_length=1000, null=True, blank=True)
    subtotal = models.FloatField(default=0)
    total = models.FloatField(default=0)
    datetime = models.DateTimeField(null=True)


class Order(models.Model):
    parent_order = models.ForeignKey(ParentOrder, on_delete=models.CASCADE)
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE, null=True)
    status = models.CharField(max_length=200, choices=ORDER_STATUS_CHOICES, default='not handled')
    subtotal = models.FloatField(default=0)
    total = models.FloatField(default=0)


class OrderItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    price = models.FloatField()
    quantity = models.IntegerField(default=1)


class OrderItemStyleGroup(models.Model):
    style_group = models.ForeignKey(StyleGroup, on_delete=models.SET_NULL, null=True)
    order_item = models.ForeignKey(OrderItem, on_delete=models.CASCADE)
    selected_style = models.ForeignKey(Style, on_delete=models.SET_NULL, null=True)


class OrderItemStyle(models.Model):
    style = models.ForeignKey(Style, on_delete=models.SET_NULL, null=True)
    order_item_style_group = models.ForeignKey(OrderItemStyleGroup, on_delete=models.CASCADE)


class CustomUserManager(BaseUserManager):

    def _create_user(self, email, password, first_name, last_name, **extra_fields):
        if not email:
            raise ValueError('Email must be provided')
        if not password:
            raise ValueError('Password is not provided')

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            **extra_fields
        )

        user.set_password(password)
        user.save()

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, first_name, last_name, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, first_name, last_name, **extra_fields)

    def create_superuser(self, email, password, first_name, last_name, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(email, password, first_name, last_name, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(db_index=True, unique=True, max_length=100)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    seller = models.ForeignKey(Seller, null=True, blank=True, on_delete=models.SET_NULL)

    registration_code = models.CharField(max_length=10, null=True, blank=True)
    design_requests = models.TextField(max_length=2000, null=True, blank=True)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'


class SellerApplication(models.Model):
    email = models.EmailField(max_length=100)
    shop_name = models.CharField(max_length=400)

    def __str__(self):
        return self.shop_name


type_choices = {
    ('buyer', 'buyer'),
    ('seller', 'seller'),}


class FAQGroup(models.Model):
    title = models.CharField(max_length=300)
    type = models.CharField(max_length=30, choices=type_choices, null=True)

    def __str__(self):
        return self.title


class FAQ(models.Model):
    title = models.CharField(max_length=300)
    answer = models.TextField(max_length=1000)
    group = models.ForeignKey(FAQGroup, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.title


class SellerFAQ(models.Model):
    question = models.CharField(max_length=300)
    answer = models.TextField(max_length=1000)
    seller = models.ForeignKey(Seller, null=True, on_delete=models.CASCADE)

    last_updated = models.DateTimeField(null=True, auto_now=True)

    def __str__(self):
        return self.title


class HelpMessage(models.Model):
    email = models.EmailField(max_length=100)
    message = models.TextField(max_length=1000)

    def __str__(self):
        return self.email


class NewsletterEmail(models.Model):
    email = models.EmailField(max_length=100)
    datetime = models.DateTimeField(null=True)

    def __str__(self):
        return self.email

shop/templates/shop/LATIGGA_home.html
{% extends "shop/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}


{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'shop/LATIGGA_home_style.css' %}">


<div id="home-wrapper">
    <div id="home">
        <div class="left">
            <p class="title">unique jewelry for every occasion</p>
            <a class="link-shop" href="/shop/{{seller}}">Shop all items<img class="arrow-right" src="/media/icons/arrow-right-black.png"></a>
            <img id="image-home-left" src="/media/home/latigga_home_2.png">
        </div>

        <div class="right">
            <img id="image-home-right" src="/media/home/latigga_home_1.png">
            <p class="quote">“My creativity gives me much joy and I’m happy I can share it with you. <br>I’m constantly searching for unique jewelry supplies to be able to create one of a kind jewelry. I love to combine supplies, various elements, metals, wood to create lovely pieces. I love to personalize the objects to give them this special touch.”</p>
        </div>
    </div>
</div>

<div class="recommendations-wrapper">
    <div class="recommendations">
        <div class="recommendations-upper">
            <p class="recommendations-h1">Items you might like</p>
            <p class="recommendations-h2">Recommendations for you</p>

            <div class="items-wrapper">
                <div class="items"  id="similarItems">
                {% for item in recommended_items %}
                    <div class="item" onclick="window.location.href='/item/{{seller}}/{{item.id}}'">
                        <img class="recommended-item-image recommended-item-first-image" id="item-first-image-similar-{{item.id}}" src="{{item.image_set.first.image.url}}" onmouseenter="showSecondImage({{item.id}}, 'similar')" onmouseleave="showFirstImage({{item.id}}, 'similar')" width="250px" alt="">
                        <img class="recommended-item-image recommended-item-second-image" id="item-second-image-similar-{{item.id}}" src="{{item.image_set.last.image.url}}" onmouseenter="showSecondImage({{item.id}}, 'similar')" onmouseleave="showFirstImage({{item.id}}, 'similar')" width="250px" alt="">

                        <p class="recommended-item-title">{{ item.title|truncatechars:30 }}</p>
                        <p class="recommended-item-price"> {{ item.price|floatformat:2 }}€<p/>
                    </div>
                {% endfor %}
                </div>
                <button class="scroll-button scroll-button-left" id="scroll-button-left-similar" onclick="scrollItems('similar', -1)"><img class="image-dropdown" src="/media/icons/arrow-right-black.png" alt=""></button>
                <button class="scroll-button" id="scroll-button-right-similar" onclick="scrollItems('similar', 1)"><img class="image-dropdown" src="/media/icons/arrow-right-black.png" alt=""></button>
            </div>
        </div>

        <div class="recommendations-lower">
            <p class="recommendations-h1">In Focus</p>
            <p class="recommendations-h2">Recommendations for you</p>

            <div class="items-wrapper">
                <div class="items"  id="completeItems">
                {% for item in focused_items %}
                    <div class="item" onclick="window.location.href='/item/{{seller}}/{{item.id}}'">
                        <img class="recommended-item-image recommended-item-first-image" id="item-first-image-complete-{{item.id}}" src="{{item.image_set.first.image.url}}" onmouseenter="showSecondImage({{item.id}}, 'complete')" onmouseleave="showFirstImage({{item.id}}, 'complete')" width="250px" alt="">
                        <img class="recommended-item-image recommended-item-second-image" id="item-second-image-complete-{{item.id}}" src="{{item.image_set.last.image.url}}" onmouseenter="showSecondImage({{item.id}}, 'complete')" onmouseleave="showFirstImage({{item.id}}, 'complete')" width="250px" alt="">

                        <p class="recommended-item-title">{{ item.title|truncatechars:30 }}</p>
                        <p class="recommended-item-price"> {{ item.price|floatformat:2 }}€<p/>
                    </div>
                {% endfor %}
                </div>
                <button class="scroll-button scroll-button-left" id="scroll-button-left-complete" onclick="scrollItems('complete', -1)"><img class="image-dropdown" src="/media/icons/arrow-right-black.png" alt=""></button>
                <button class="scroll-button" id="scroll-button-right-complete" onclick="scrollItems('complete', 1)"><img class="image-dropdown" src="/media/icons/arrow-right-black.png" alt=""></button>
            </div>
        </div>
    </div>
</div>


<script>
    function scrollItems(items, direction){
        str = items + 'Items'
        console.log(str)
        items_element = document.getElementById(str)
        let width = (items_element.offsetWidth + 25) * direction;
        console.log(width)
        items_element.scrollBy(width, 0)

        let btn_left_str = 'scroll-button-left-' + items
        btn_left = document.getElementById(btn_left_str)
        console.log((items_element.scrollLeft + width))
        if((items_element.scrollLeft + width) <= 0){
            btn_left.style.display = 'None'
        }
        else{
            btn_left.style.display = 'block'
        }
    }

    function showSecondImage(item_id, items){
        item_first_image_id = 'item-first-image-' + items + '-' + item_id
        item_second_image_id = 'item-second-image-' + items + '-' + item_id
        document.getElementById(item_first_image_id).style.display = 'None';
        document.getElementById(item_second_image_id).style.display = 'block';
    }

    function showFirstImage(item_id, items){
        item_first_image_id = 'item-first-image-' + items + '-' + item_id
        item_second_image_id = 'item-second-image-' + items + '-' + item_id
        document.getElementById(item_first_image_id).style.display = 'block';
        document.getElementById(item_second_image_id).style.display = 'None';
    }
</script>




{% endblock %}

shop/templates/shop/home_dashboard.html
{% extends "shop/base_dashboard.html" %}

{% block title %}Home{% endblock %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'shop/home_dashboard_style.css' %}">

<!--
<nav class="navbar-left">
    <a href="/"><img id="logo-nav" src="/media/logos/logo.png"></a>


    <ul class="dashboard-links">
        <li class="dashboard-link nav-home active-page" id="navigation-dashboard-link-dashboard"><a href="/dashboard/home/{{seller}}"><img class="icon-navbar" src="/media/icons/home-dashboard-white.png" alt="">Dashboard</a></li>
        <li class="dashboard-link nav-listings" id="navigation-dashboard-link-listings"><a href="/dashboard/listings/{{seller}}"><img class="icon-navbar" src="/media/icons/listings-dashboard-white.png" alt="">Listings</a></li>
        <li class="dashboard-link nav-deliveries" id="navigation-dashboard-link-deliveries"><a href="/dashboard/deliveries/last/{{seller}}"><img class="icon-navbar" src="/media/icons/deliveries-dashboard-white.png" alt="">Orders</a></li>
        <li class="dashboard-link nav-settings" id="navigation-dashboard-link-settings"><a href="/dashboard/settings/{{seller}}"><img class="icon-navbar" src="/media/icons/settings-dashboard-white.png" alt="">Settings</a></li>
    </ul>

</nav>

<nav class="navbar-mobile">
    <a href="/"><img id="logo-nav" src="/media/logos/logo.png"></a>

    <ul class="dashboard-links">
        <li class="dashboard-link nav-home active-page" id="navigation-dashboard-link-dashboard"><a href="/dashboard/home/{{seller}}"><img class="icon-navbar" src="/media/icons/home-dashboard-white.png" alt="">Home</a></li>
        <li class="dashboard-link nav-listings" id="navigation-dashboard-link-listings"><a href="/dashboard/listings/{{seller}}"><img class="icon-navbar" src="/media/icons/listings-dashboard-white.png" alt="">Listings</a></li>
        <li class="dashboard-link nav-deliveries" id="navigation-dashboard-link-deliveries"><a href="/dashboard/deliveries/last/{{seller}}"><img class="icon-navbar" src="/media/icons/deliveries-dashboard-white.png" alt="">Orders</a></li>
        <li class="dashboard-link nav-settings" id="navigation-dashboard-link-settings"><a href="/dashboard/settings/{{seller}}"><img class="icon-navbar" src="/media/icons/settings-dashboard-white.png" alt="">Settings</a></li>
    </ul>

</nav>
-->

<nav id="header">
    <p id="header-title">
        <img class="icon-header" src="/media/icons/home-dashboard.png" alt="">
        Dashboard
    </p>
</nav>

<div class="mainmain">

    <div class="container">
        <div class="element element1" id="element-sales">
            <p class="element-title">
                <img class="icon-dashboard" src="/media/icons/orders-dashboard.png" alt="">
                Sales
            </p>
            <div id="sales-chart-wrapper">
                <canvas id="sales-chart"></canvas>
            </div>
        </div>
        <div class="element element2">
            <p class="element-title">
                <img class="icon-dashboard" src="/media/icons/revenue-dashboard.png" alt="">
                Revenue
            </p>
            <div class="statistic-wrapper" id="revenue-wrapper">
                <p class="statistic-number">{{revenue|floatformat:2}}€</p>
                <p class="statistic-change"><img class="icon-arrow-up" src="/media/icons/arrow_green.svg" alt=""><span>{{revenue_change|floatformat:2}}%</span> more than last month</p>
            </div>
            <a class="showMore-link" href="/dashboard/deliveries/last/{{seller}}">
                <div class="showMore-wrapper">
                    <p class="showMore-text">Show more</p>
                    <img class="icon-arrow-right" src="/media/icons/arrow-right-black.png" alt="">
                </div>
            </a>
        </div>
        <div class="element element3">
            <p class="element-title">
                <img class="icon-dashboard" src="/media/icons/pagevisits-dashboard.png" alt="">
                Page Visits
            </p>
            <div class="statistic-wrapper" id="pageVisits-wrapper">
                <p class="statistic-number">0 <span style="font-size: 20;">(coming soon)</span></p>
                <p class="statistic-change"><img class="icon-arrow-up" src="/media/icons/arrow_green.svg" alt=""><span>0%</span> more than last month</p>
            </div>
            <a class="showMore-link" href="/dashboard/deliveries/last/{{seller}}">
                <div class="showMore-wrapper">
                    <p class="showMore-text">Show more</p>
                    <img class="icon-arrow-right" src="/media/icons/arrow-right-black.png" alt="">
                </div>
            </a>
        </div>
        <div class="element element4">
            <div class="element4-header">
                <p class="element-title">
                    <img class="icon-dashboard" src="/media/icons/listings-dashboard.png" alt="">
                    Listings
                </p>
                <a class="showMore-link" href="/dashboard/listings/{{seller}}">
                    <div class="showMore-wrapper-element4">
                        <p class="showMore-text">Show all</p>
                        <img class="icon-arrow-right" src="/media/icons/arrow-right-black.png" alt="">
                    </div>
                </a>
            </div>

            <div class="items" id="items">
                {% for item in items %}
                    <div class="item" onclick="window.location.href='/item/{{seller}}/{{item.id}}'">

                        <img class="item-image item-first-image" id="item-first-image-{{item.id}}" src="{{item.image_set.first.image.url}}" onmouseenter="showSecondImage({{item.id}})" onmouseleave="showFirstImage({{item.id}})" width="250px" alt="">
                        <img class="item-image item-second-image" id="item-second-image-{{item.id}}" src="{{item.image_set.last.image.url}}" onmouseenter="showSecondImage({{item.id}})" onmouseleave="showFirstImage({{item.id}})" width="250px" alt="">

                        <p class="item-title">{{ item.title|truncatechars:15 }}</p>
                        <p class="item-price"> {{ item.price|floatformat:2 }}€<p/>
                        <p class="items-sold"><img class="items-sold-img" src="/media/icons/items-sold.png">{{item.sold_counter}} sold</p>

                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="element element5">
            <div class="element5-header">
                <p class="element-title">
                    <img class="icon-dashboard" src="/media/icons/deliveries-dashboard.png" alt="">
                    Orders
                </p>
                <a class="showMore-link" href="/dashboard/deliveries/last/{{seller}}">
                    <div class="showMore-wrapper-element5">
                        <p class="showMore-text">Show all</p>
                        <img class="icon-arrow-right" src="/media/icons/arrow-right-black.png" alt="">
                    </div>
                </a>
            </div>
            <div id="deliveries">

                <div class="header-orderlist">
                     <img class="box"
                            src="/media/icons/box-to-tick.png" alt="">
                    <p class="header-orderId">Order ID</p>
                    <p class="header-orderDate">Date</p>
                    <p class="header-orderStatus">Status</p>
                </div>

                <div class="orderlist">
                    {% for order in orders %}
                    <a href="/dashboard/deliveries/{{order.id}}/{{seller}}">
                        <div class="orderlist-object" id="orderlist-object-{{order.id}}" style="{%if order.id == selected_order.id%}background-color: #f8f8f8{%endif%}">
                            <img class="box"
                                src="/media/icons/box-to-tick.png" alt="">
                                <p class="orderId">{{order.id}}</p>
                                <p class="orderDate">{{order.parent_order.datetime|date:"d.m.y"}}</p>
                                <div class="orderStatus orderStatus-{{order.status|cut:' '}}">
                                    <img class="orderStatus-icon" src="/media/icons/shipping-black.png" alt="">
                                    <p class="orderStatus-text">{{order.status}}</p>
                                </div>
                        </div>
                    </a>
                    {% endfor %}
            </div>
            </div>
        </div>
    </div>
</div>

<script>
  const labels = {{weekday_list|safe}};

  const data = {
    labels: labels,
    datasets: [{
      label: 'Sales',
      backgroundColor: '#C6D9D2',
      borderColor: '#C6D9D2',
      data: {{sales_list}},
    }]
  };

  const config = {
    type: 'line',
    data: data,
    options: {
        maintainAspectRatio: false,
        plugins: {
            legend: {
              display: false
            }
        },
        scale: {
            ticks: {
                precision: 0
            }
        }
    }
  };

   const salesChart = new Chart(
        document.getElementById('sales-chart'),
        config
    );

</script>

{% endblock %}

shop/templates/shop/settings_dashboard_policies.html
<form id="policiesForm" method="post" action="">
    {% csrf_token %}
    <div class="settings-block1">
        <p class="block-heading">Shipping</p>
        <div class="settings-block1-fields">
            <div class="input-group">
                {{policies_form.shipping_general_information}}
                <label for="id_shipping_general_information">General Information</label>
            </div>
            <div class="input-group">
                {{policies_form.shipping_customs_and_taxes}}
                <label for="id_customs_and_taxes">Customs and Import Taxes</label>
            </div>
        </div>
    </div>

    <div class="settings-block2">
        <p class="block-heading">Returns & Exchanges</p>
        <div class="block2-upper">
            <div class="block2-boxes">
                <p class="block2-text">I accept...</p>
                {{policies_form.accepts_returns}}
                <label for="id_accepts_returns">returns</label><br>
                {{policies_form.accepts_exchanges}}
                <label for="id_accepts_exchanges">exchanges</label><br>
                {{policies_form.accepts_cancellations}}
                <label for="id_accepts_cancellations">cancellations</label><br><br>
            </div>

            <div class="block2-details">
                <p class="block2-text G1">Contact me within</p>{{policies_form.contact_within}}<p class="block2-text G2">days of delivery</p>
                <p class="block2-text G3">Ship items back within</p>{{policies_form.ship_back_within}}<p class="block2-text G4">days of delivery</p>
                <p class="block2-text G5">Request a cancellation</p>{{policies_form.request_cancellation}}
            </div>
        </div>

        <div class="settings-block1-fields">
            <div class="input-group">
                {{policies_form.returns_conditions}}
                <label for="id_returns_conditions">Conditions of Returns</label>
            </div>
            <div class="input-group">
                {{policies_form.returns_questions}}
               <label for="id_returns_questions">Questions about your Order?</label>
            </div>
        </div>
    </div>

    <div class="settings-block3">
        <p class="block-heading">Privacy Policy</p>
        <div class="settings-block3-fields">
            <div class="input-group">
                {{policies_form.privacy}}
                <label for="id_privacy">Privacy Policy</label>
            </div>
        </div>
    </div>
</form>